# Generated by Django 2.2.7 on 2020-01-08 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artists',
            new_name='artist',
        ),
    ]
